name: Terraform ALB Path Routing

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write  # Required for OIDC
  contents: read   # Required for actions/checkout

jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::650251701672:role/s3-github
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7  # or your preferred version
     
    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
